# Generated by Django 3.0.2 on 2020-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mailer_sended'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailer',
            name='subject',
            field=models.TextField(default='no subject'),
        ),
    ]
